import React, {useState} from 'react'
import Head from 'next/head'
import Navigation from '../components/Navigation'
import Drawer from '../components/Drawer'
import Footer from '../components/Footer'

export default function About() {
    const [isOpen, setIsOpen] = useState(false);

    const toggleCart = () => {
      setIsOpen(!isOpen)
    }

    
    return (
        <div>
            <Head>
                <title>About - Earthlone</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Navigation toggleCart={toggleCart} />
                <div className="bg-gray-500 h-48 flex justify-center"><h2 className="my-auto text-white"> <span className="font-semibold">About</span> Us</h2></div>
                <div className="text-center container mx-auto my-4 px-8">
                    <h4 className="sticky font-semibold mb-4">Who Are We</h4>
                    <h6 className="mb-6">A small project to raise awareness of the environment and provide solutions to apply that concern.</h6>
                    <h4 className="sticky font-semibold mb-4">Our Vision</h4>
                    <h6 className="mb-6">To be a pioneer in sustainable living in Indonesia. </h6>
                    <h4 className="sticky font-semibold mb-4">Our Mission</h4>
                    <h6 className="mb-6">To accelerate the distribution of eco-friendly products in Indonesia. </h6>
                </div>
                <Drawer isOpen={isOpen} toggleCart={toggleCart} setIsOpen={setIsOpen}/>
                <Footer/>
            </main>
        </div>
    )
}