import Head from 'next/head'
import { useState } from 'react';
import Navigation from '../components/Navigation'
import Drawer from '../components/Drawer'
import Footer from '../components/Footer'
import { AiOutlineClose } from 'react-icons/ai'

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);

  const toggleCart = () => {
    setIsOpen(!isOpen)
  }

  return (
    <div className=''>
      <Head>
        <title>Earthlone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section>
          <Navigation toggleCart={toggleCart} />
          <div className="bg-gray-500 h-96 flex flex-col justify-center text-center relative">
            <h1 className="text-black font-semibold z-0 relative"> Welcome to <span className="text-white font-semibold">Earthlone</span></h1>
            <h6 className="text-white">Right now, <span className="text-white">Earth</span> is <span className="text-white">alone</span>. Earth is your only home.</h6>
          </div>
        </section>
          <Drawer isOpen={isOpen} toggleCart={toggleCart} setIsOpen={setIsOpen}/>
      <Footer />
      </main>

    </div>
  )
}